version: '3.7'
services:
    myapp:
        image: myimage:latest
        container_name: myimagecont
        hostname: localhost
        init: true
        ports:
            - "8081:8080"
        volumes:
          - type: bind
            source: ./myapppersistence
            target: /etc/todos
            read_only: false
        expose:
            - "8080"
